### ISSUE TITLE
Create a new pub.dev package out of this

### ISSUE THREAD

**Issue by Ahmadre** [arianneorpilla/material_floating_search_bar#2]
@lrorpilla can we have a pub package for this?

It would help to make this public and official (of course with a note that this is a fork)

Maybe like: `material_floating_search_bar_2`

**Comment by AlwinFassbender** [comment]
I forked this repository, fixed some stuff for newer Flutter versions and uploaded the package to [pub.dev](https://pub.dev/packages/material_floating_search_bar_2), similar to other packages of bxqm that are not maintained anymore (example: https://pub.dev/packages/implicitly_animated_reorderable_list_2). I will try to maintain it when flutter version changes make it necessary. Feel free to leave any remarks for this package over there. 

https://github.com/AlwinFassbender/material_floating_search_bar

**Comment by arianneorpilla** [comment]
Thanks for taking over, unfortunately I already have my hands full maintaining my own forks of packages that suddenly got dropped from pub or had maintainers disappear so I really appreciate that you've done so for this.
